export {default as LandingPage} from './LandingPage';
export {default as HomePage} from './HomePage';
export {default as DiagnoseStartPage} from './DiagnoseStartPage';
export {default as ResultsPage} from './ResultsPage'
export {default as Pain1} from './painPages/pain1';
export {default as Pain2} from './painPages/pain2';
export {default as Pain3} from './painPages/pain3';
export {default as Pain4} from './painPages/pain4';
export {default as Swelling1} from './swellingPages/swelling1';
export {default as Ulcer1} from './ulcerPages/ulcer1';
export {default as Common1} from './commonPages/common1';